

locals {
  add_patch_to_ks = var.flux_patch_gotk ? local.patch_ks : ""
  patch_ks        = <<YAML

patchesStrategicMerge:
  - gotk_patch.yaml
YAML

  patch = <<YAML
# 
# READ ONLY
# This file is generated by terraform, any direct edits will be overwritten on the next apply
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-automation-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 64Mi
YAML
}

resource "github_repository_file" "gotk_patch" {
  count               = var.flux_enabled && var.flux_patch_gotk ? 1 : 0
  repository          = data.github_repository.main[0].name
  file                = "${var.flux_target_path}/${local.flux_manifests_path}/gotk_patch.yaml"
  content             = local.patch
  branch              = var.flux_branch
  overwrite_on_create = true
  lifecycle {
    ignore_changes = [content, sha]
  }
}
